language: node_js
node_js:
  - "5.1"
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
before_install:
  - 'if [ "${TRAVIS_NODE_VERSION}" != "0.9" ]; then case "$(npm --version)" in 1.*) npm install -g npm@1.4.28 ;; 2.*) npm install -g npm@2 ;; esac ; fi'
  - 'if [ "${TRAVIS_NODE_VERSION}" != "0.6" ] && [ "${TRAVIS_NODE_VERSION}" != "0.9" ]; then npm install -g npm; fi'
script:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "4.2" ]; then npm run lint && npm test ; else npm test'
env:
  - REACT=0.14
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "5.0"
    - node_js: "4.1"
    - node_js: "4.0"
    - node_js: "0.11"
